AWSTemplateFormatVersion: 2010-09-09
Description: gws-contact-handler
Transform: AWS::Serverless-2016-10-31

Resources:
  ZohoDeskRefreshToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "zoho-desk-refresh-token-1"
      Description: "Secret for Zoho Desk oauth token."
      SecretString: " "
  
  ContactApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: API Gateway for GWS website
      StageName: Prod

  ContactHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ./dist
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          ZOHO_CLIENT_ID: String
          ZOHO_CLIENT_SECRET: String
          ZOHO_GRANT_TOKEN: String
          ZOHO_DESK_DEPARTMENT_ID: String
      Policies:
        - Statement:
          - Sid: SecretsManagerAccess
            Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:PutSecretValue
            Resource: !Ref ZohoDeskRefreshToken
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApiGateway
            Path: /contact
            Method: POST

Outputs:
  ContactApiGateway:
    Description: "API Gateway endpoint URL for Staging stage"
    Value: !Sub "https://${ContactApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ContactApiGateway.Stage}/contact"
  ContactApiGatewayRestApiId:
    Description: "API Gateway ARN for AWS API Gateway"
    Value: !Ref ContactApiGateway
    Export:
      Name: ContactApiGateway-RestApiId
  ContactApiGatewayRootResourceId:
    Value: !GetAtt ContactApiGateway.RootResourceId
    Export:
      Name: ContactApiGateway-RootResourceId
