import "./globals.css";

import clsx from "clsx";
import type { Metadata } from "next";

import { open_Sans } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(open_Sans.className, "container max-w-[90%] overflow-x-hidden mx-auto bg-black text-white text-justify md:text-center text-base md:text-lg")}
      >
        {children}
      </body>
    </html>
  );
}
